# Set theme
remote_theme: daviddarnes/alembic

environment: prod
# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme
- jekyll-analytics

# Site settings
url: 'https://thedarkphoenix.github.io/'
baseurl: ''
title: 'Maciej Stępień'
description: 'Projekty'
permalink: pretty
logo: "/pics/logo1.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Home: /
  About: /about/
  Projekty: /projekty/
  Kategorie: /categories/

# Footer nav
navigation_footer:
  Back to top: "#top"

# Collections
collections:
  posts:
    title: Projekty

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-138286459-1          # Required - replace with your tracking id
    anonymizeIp: true      # Optional - Default: false - set to true for anonymized tracking